#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

# the following two variables are used by the target "waf dist"
VERSION = '0.0.1'
APPNAME = 'waf-cpp-project'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'


def options(opt):
    opt.load('compiler_cxx')
    opt.add_option("--shared", action="store_true", help="build shared library")
    opt.add_option("--static", action="store_true", help="build static library")


def configure(conf):
    conf.load('compiler_cxx')


def build(bld):
    if bld.options.shared:
        bld.shlib(source="run.cpp", target="run", includes=["include"],
                  cxxflags="-g -Wall -O0")
    elif bld.options.static:
        bld.stlib(source="run.cpp", target="run", includes=["include"],
                  cxxflags="-g -Wall -O0")
    else:  # by default, build a shared library
        bld.shlib(source="run.cpp", target="run", includes=["include"],
                  cxxflags="-g -Wall -O0")

    bld.program(source="native-lib.cpp", target="native", includes=["include"],
                use="run")
    if bld.cmd != 'clean':
        from waflib import Logs
        bld.logger = Logs.make_logger('test.log', 'build')  # just to get a clean output
        bld.logger = None
